version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=82eab2ea-bbbc-4025-9858-5fa2738ec7e4.hsvc.ir
      - DB_PORT=32215
      - DB_USER=postgres
      - DB_PASSWORD=KwuujJsBtnS4cTbowdpZYjdlKy8Vk0Du
      - DB_NAME=postgres
    volumes:
      - ./templates:/app/templates
      - ./static:/app/static
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 